Repository BlueBrain/nmodl, pull requests merged in 2021-03, with the labels that each got.

#522 Improved vexp (and friends) test
  src/codegen/fast_math.hpp
  test/unit/fast_math/fast_math.cpp
Labels: enhancement

#514 defuse with pointers to the statement in a variable is used/defined
  src/visitors/defuse_analyze_visitor.cpp
  src/visitors/defuse_analyze_visitor.hpp
  test/unit/visitor/defuse_analyze.cpp
Labels: enhancement, visitor

#559 Add flexibility when using or not legacy units
  src/codegen/codegen_c_visitor.cpp
Labels: codegen

#560 Travis has been replaced by github actions
  .travis.yml
Labels: enhancement

#562 Add support for ConstantBlock
  src/codegen/codegen_c_visitor.cpp
  src/codegen/codegen_compatibility_visitor.cpp
Labels: enhancement
