Repository BlueBrain/nmodl, pull requests merged in 2022-05, with the labels that each got.

#645 Support for Breakpoint block (nrn_cur) for code generation
  src/codegen/codegen_acc_visitor.cpp
  src/codegen/codegen_c_visitor.cpp
  src/codegen/codegen_c_visitor.hpp
  src/codegen/codegen_cuda_visitor.cpp
  src/codegen/codegen_driver.cpp
  src/codegen/codegen_info.cpp
  src/codegen/codegen_info.hpp
  src/codegen/codegen_ispc_visitor.cpp
  src/codegen/codegen_naming.hpp
  src/codegen/llvm/codegen_llvm_helper_visitor.cpp
  src/codegen/llvm/codegen_llvm_helper_visitor.hpp
  src/codegen/llvm/codegen_llvm_visitor.cpp
  src/codegen/llvm/codegen_llvm_visitor.hpp
  src/codegen/llvm/llvm_ir_builder.cpp
  src/language/nmodl.yaml
  test/unit/codegen/codegen_llvm_execution.cpp
  test/unit/codegen/codegen_llvm_ir.cpp
  test/unit/codegen/codegen_llvm_visitor.cpp
Labels: wip

#853 [LLVM][GPU] Atomic updates support
  src/codegen/llvm/codegen_llvm_helper_visitor.cpp
  src/codegen/llvm/codegen_llvm_visitor.cpp
  src/codegen/llvm/llvm_ir_builder.cpp
  src/codegen/llvm/llvm_ir_builder.hpp
  test/benchmark/CMakeLists.txt
  test/unit/codegen/codegen_llvm_ir.cpp
  test/unit/codegen/codegen_llvm_visitor.cpp
Labels: gpu, llvm

#865 [LLVM][FIX] Float generation fix in LLVM helper visitor
  src/codegen/llvm/codegen_llvm_helper_visitor.cpp
  src/codegen/llvm/codegen_llvm_helper_visitor.hpp
  src/codegen/llvm/codegen_llvm_visitor.cpp
  src/codegen/llvm/codegen_llvm_visitor.hpp
  test/unit/codegen/codegen_llvm_execution.cpp
  test/unit/codegen/codegen_llvm_instance_struct.cpp
Labels: bug

#870 fixup! CI errors with sympy 1.9 and 1.10
  setup.py
  test/unit/visitor/sympy_solver.cpp
Labels: bug

#864 [LLVM][SIMD] Atomic updates support
  src/codegen/llvm/codegen_llvm_visitor.cpp
  src/codegen/llvm/llvm_ir_builder.cpp
  src/codegen/llvm/llvm_ir_builder.hpp
  test/benchmark/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/codegen/codegen_llvm_execution.cpp
  test/unit/codegen/codegen_llvm_ir.cpp
Labels: llvm
